version: "3.8"
services:

  # BACK

  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    tty: true
    volumes:
      - ./:/var/www/html

  php:
    build:
      context: ./docker/php
    container_name: php
    restart: always
    tty: true
    volumes:
      - ./:/var/www/html